---
title: "lab5"
author: "Adam VanGorp"
date: "11/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. 
``` {r}
diabetes<-read.table('diabetes.txt',header=TRUE)
head(diabetes)
```
2.
``` {r}
library(tidyverse)
index.na=apply(is.na(diabetes), 1, any)
index.na
head(diabetes)
str(diabetes)
```
3.
``` {r}
diabetes_reduced <- select(diabetes, -c(id, bp.2s, bp.2d))
```
4.
```{r}
index.na1=apply(is.na(diabetes_reduced), 1, any)
index.na1
diabetes_clean <- diabetes_reduced[complete.cases(diabetes_reduced),]
```

5.
``` {r}
index.na2=apply(is.na(diabetes_clean), 1, any)
index.na2
```
To see if all rows that have missing values were dropped we just have to run the given line of code again. If there are no results then there are no missing values. 

6.
Taking the log value of glyhb would make the data less right-skewed and more symmetric.
``` {r}

```

7.
``` {r}
ggplot(diabetes_clean, aes(glyhb)) + geom_histogram()
diabetes_clean$glyhb_star = log(diabetes_clean$glyhb)
ggplot(diabetes_clean, aes(glyhb_star)) + geom_histogram()

```

8.
``` {r}
diabetes_clean %>% group_by(frame) %>% summarise(mean.glyhb = mean(glyhb_star))
```

9.
``` {r}

```

10.
``` {r}

```

11.
``` {r}

```

12.
``` {r}

```

13.
``` {r}

```

14.
``` {r}

```

15.
``` {r}

```
